import test from 'node:test'
import assert from 'node:assert/strict'
import {
  AUDIO_DEFAULT_MESSAGE,
  AUDIO_DEFAULT_TITLE,
  AUDIO_MAX_BYTES,
  buildAudioStoragePath,
  getAudioContentType,
  getAudioExtension,
  getSupportedRecordingMimeType,
  validateAudioFile
} from './audio.js'

function fileLike(name, type, size = 1024) {
  return { name, type, size }
}

test('accepts supported audio MIME types under 10MB', () => {
  const result = validateAudioFile(fileLike('voz.webm', 'audio/webm', AUDIO_MAX_BYTES))

  assert.deepEqual(result, { valid: true, error: null })
})

test('accepts ogg audio generated by mobile browsers', () => {
  const result = validateAudioFile(fileLike('voz.ogg', 'audio/ogg', 2048))

  assert.deepEqual(result, { valid: true, error: null })
})

test('rejects unsupported audio formats', () => {
  const result = validateAudioFile(fileLike('voz.aac', 'audio/aac'))

  assert.equal(result.valid, false)
  assert.match(result.error, /MP3, WAV, WEBM, M4A, MP4 ou OGG/)
})

test('rejects files without extension when MIME type is unsupported', () => {
  const result = validateAudioFile(fileLike('recording', 'audio/aac'))

  assert.equal(result.valid, false)
  assert.match(result.error, /MP3, WAV, WEBM, M4A, MP4 ou OGG/)
})

test('rejects audio files bigger than 10MB', () => {
  const result = validateAudioFile(fileLike('voz.mp3', 'audio/mpeg', AUDIO_MAX_BYTES + 1))

  assert.equal(result.valid, false)
  assert.match(result.error, /10MB/)
})

test('detects extension from filename or MIME type', () => {
  assert.equal(getAudioExtension(fileLike('voz.M4A', 'audio/x-m4a')), 'm4a')
  assert.equal(getAudioExtension(fileLike('recording', 'audio/webm')), 'webm')
  assert.equal(getAudioExtension(fileLike('voz', 'audio/mp4')), 'mp4')
  assert.equal(getAudioExtension(fileLike('voz', 'audio/ogg')), 'ogg')
})

test('falls back to audio/webm content type when file type is empty', () => {
  assert.equal(getAudioContentType(fileLike('voz.webm', '')), 'audio/webm')
})

test('chooses the first MediaRecorder MIME type supported by the browser', () => {
  const isTypeSupported = (type) => type === 'audio/mp4'

  assert.equal(getSupportedRecordingMimeType(isTypeSupported), 'audio/mp4')
})

test('builds a scoped storage path for the current gift slug', () => {
  const path = buildAudioStoragePath(fileLike('minha voz.webm', 'audio/webm'), 'abc123', 1770000000000, () => 0.5)

  assert.equal(path, 'audios/abc123/audio-1770000000000-i.webm')
})

test('exposes default audio copy', () => {
  assert.equal(AUDIO_DEFAULT_TITLE, 'Escuta isso com carinho')
  assert.equal(AUDIO_DEFAULT_MESSAGE, 'Eu gravei esse audio pensando em voce.')
})
